version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-n8n
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: Merced1129
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: Merced1129
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: claveFuerte123
      WEBHOOK_URL: https://n8n.grupoganesha.net
      N8N_HOST: n8n.grupoganesha.net
      N8N_PORT: 443
      N8N_PROTOCOL: https
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  n8n_data:
  npm_data:
  npm_letsencrypt:
